version: '3.1'

services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    environment:
      USERNAME: 'describly2@gmail.com'
      PASSWORD: 'K2s@12345'
      DEBUG: 0
