name: Docker

on:
  push:
    branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP 5.6
        uses: shivammathur/setup-php@v2
        with:
          php-version: '5.6'

      - name: Cheking PHP Version
        run: php -v

      - name: Running the test
        run: php app/Main.php
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
