name: Docker

on:
  push:
    branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: running the image
        run: |
          docker-compose run -e USERNAME=${{ secrets.USERNAME }} -e PASSWORD=${{ secrets.PASSWORD }} app sh -c "php Main.php"
